<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { useRoute } from 'vue-router'
import SiteShell from '../../components/SiteShell.vue'
import { getApplication, reviewApplication } from '../../features/dealership/api'
import { applicationLabels, businessLabels, type DealerApplication } from '../../features/dealership/types'
import '../../features/dealership/style.css'
const route = useRoute(); const application = ref<DealerApplication | null>(null); const decision = ref<'APPROVE' | 'REJECT'>('APPROVE'); const publicReason = ref(''); const internalNote = ref(''); const existingCompanyId = ref(''); const loading = ref(true); const busy = ref(false); const error = ref('')
async function load() { try { application.value = await getApplication(route.params.id as string, true) } catch (cause) { error.value = (cause as Error).message } finally { loading.value = false } }
async function submit() { if (!application.value) return; busy.value = true; error.value = ''; try { application.value = await reviewApplication(application.value.id, { applicationVersion: application.value.currentContentVersion, decision: decision.value, publicReason: publicReason.value || null, internalNote: internalNote.value || null, existingCompanyId: existingCompanyId.value || null }); ElMessage.success('审核结果已保存') } catch (cause) { error.value = (cause as Error).message } finally { busy.value = false } }
onMounted(load)
</script>
<template><SiteShell title="申请审核" admin eyebrow="OPERATIONS / APPLICATION REVIEW"><div v-if="loading" class="dealer-empty">正在读取申请…</div><p v-else-if="error && !application" class="error-summary">{{ error }}</p><template v-else-if="application"><section class="dealer-detail-head"><div><span class="dealer-status" :data-status="application.status">{{ applicationLabels[application.status] }}</span><p>{{ application.applicationNumber }} · 当前内容 v{{ application.currentContentVersion }}</p></div><RouterLink class="secondary-button" to="/admin/dealer-applications">返回队列</RouterLink></section><p v-if="application.suspectedDuplicate" class="dealer-duplicate">同名同地区企业已存在。该提示不代表自动合并，请核对主账户归属。</p><p v-if="error" class="error-summary">{{ error }}</p><div class="dealer-detail-grid"><section v-for="version in application.versions" :key="version.contentVersion" class="paper-section"><h2>申请内容 v{{ version.contentVersion }}</h2><dl class="dealer-data"><div><dt>企业名称</dt><dd>{{ version.companyName }}</dd></div><div><dt>业务类型</dt><dd>{{ businessLabels[version.businessType] }}</dd></div><div><dt>地区</dt><dd>{{ version.countryOrRegion }} · {{ version.city }}</dd></div><div><dt>联系人</dt><dd>{{ version.contactName }} · {{ version.phone }}</dd></div><div><dt>合作邮箱</dt><dd>{{ version.cooperationEmail }}</dd></div><div><dt>网站</dt><dd>{{ version.website || '未填写' }}</dd></div><div><dt>经营渠道</dt><dd>{{ version.businessChannels }}</dd></div><div><dt>合作意向</dt><dd>{{ version.cooperationIntent }}</dd></div><div><dt>公开渠道意愿</dt><dd>{{ version.publicChannelConsent ? '已同意' : '未同意' }}</dd></div></dl></section><aside class="paper-section"><h2>历史审核</h2><div v-if="!application.reviews.length" class="dealer-empty compact">尚无审核记录</div><article v-for="review in application.reviews" :key="review.contentVersion" class="dealer-review-note">v{{ review.contentVersion }} · {{ review.decision }}<p>{{ review.publicReason || '无公开说明' }}</p><small>{{ review.internalNote || '无内部备注' }}</small></article></aside></div><section v-if="application.status === 'PENDING'" class="paper-section dealer-review-form"><h2>处理当前版本</h2><div class="dealer-choice"><label><input v-model="decision" value="APPROVE" type="radio" /> 通过并激活合作</label><label><input v-model="decision" value="REJECT" type="radio" /> 驳回并允许修订</label></div><label v-if="decision === 'REJECT'">申请人可见原因<textarea v-model="publicReason" maxlength="500"></textarea></label><label>内部备注<textarea v-model="internalNote" maxlength="2000"></textarea></label><label>关联现有企业 ID（仅限当前申请人的企业，可选）<input v-model="existingCompanyId" /></label><button class="primary-button" type="button" :disabled="busy || (decision === 'REJECT' && publicReason.trim().length < 2)" @click="submit">{{ busy ? '保存中…' : '确认审核结果' }}</button></section></template></SiteShell></template>
