<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import SiteShell from '../../components/SiteShell.vue'
import { channelStatus, createChannel, getAdminChannels, updateChannel } from '../../features/dealership/api'
import type { Channel } from '../../features/dealership/types'
import '../../features/dealership/style.css'
const channels = ref<Channel[]>([]); const editing = ref<Channel | null>(null); const loading = ref(true); const busy = ref(false); const error = ref('')
const form = reactive({ name: '', countryOrRegion: '中国', city: '', address: '', phone: '', website: '', companyId: '' })
function clear() { editing.value = null; Object.assign(form, { name: '', countryOrRegion: '中国', city: '', address: '', phone: '', website: '', companyId: '' }) }
function edit(channel: Channel) { editing.value = channel; Object.assign(form, { name: channel.name, countryOrRegion: channel.countryOrRegion, city: channel.city, address: channel.address, phone: channel.phone, website: channel.website ?? '', companyId: channel.companyId ?? '' }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
async function load() { loading.value = true; try { channels.value = (await getAdminChannels()).items } catch (cause) { error.value = (cause as Error).message } finally { loading.value = false } }
async function save() { busy.value = true; error.value = ''; try { const body = { ...form, website: form.website || null, companyId: form.companyId || null, expectedVersion: editing.value?.version ?? null }; if (editing.value) await updateChannel(editing.value.id, body); else await createChannel(body); ElMessage.success(editing.value ? '渠道已更新' : '渠道草稿已创建'); clear(); await load() } catch (cause) { error.value = (cause as Error).message } finally { busy.value = false } }
async function toggle(channel: Channel) { try { const result = await ElMessageBox.prompt(`请输入${channel.published ? '下线' : '发布'}原因`, '渠道状态确认', { inputPattern: /^.{2,500}$/, inputErrorMessage: '请填写 2—500 个字符' }); await channelStatus(channel, !channel.published, result.value); ElMessage.success(channel.published ? '渠道已下线' : '渠道已发布'); await load() } catch (cause) { if (cause instanceof Error && cause.message) error.value = cause.message } }
onMounted(load)
</script>
<template><SiteShell title="公开渠道管理" admin eyebrow="OPERATIONS / CHANNELS"><section class="paper-section"><div class="section-heading"><div><p>{{ editing ? 'EDIT CHANNEL' : 'NEW CHANNEL' }}</p><h2>{{ editing ? '编辑渠道公开字段' : '建立未发布渠道' }}</h2></div><button v-if="editing" class="text-button" type="button" @click="clear">取消编辑</button></div><p v-if="error" class="error-summary">{{ error }}</p><form class="dealer-form" @submit.prevent="save"><label>渠道名称<input v-model="form.name" maxlength="100" required /></label><label>国家／地区<input v-model="form.countryOrRegion" maxlength="100" required /></label><label>城市<input v-model="form.city" maxlength="100" required /></label><label>联系电话<input v-model="form.phone" maxlength="40" required /></label><label class="wide">公开地址<input v-model="form.address" maxlength="200" required /></label><label>网站（可选）<input v-model="form.website" type="url" maxlength="2048" /></label><label>关联企业 ID（可选）<input v-model="form.companyId" placeholder="需有公开意愿且合作有效" /></label><div class="wide dealer-form-actions"><button class="primary-button" type="submit" :disabled="busy">{{ busy ? '保存中…' : editing ? '保存渠道修改' : '创建渠道草稿' }}</button></div></form></section><section class="paper-section"><h2>渠道记录</h2><div v-if="loading" class="dealer-empty">正在读取渠道…</div><div v-else class="dealer-list"><article v-for="channel in channels" :key="channel.id"><div><p>{{ channel.countryOrRegion }} · {{ channel.city }}</p><h2>{{ channel.name }}</h2><span>{{ channel.address }} · v{{ channel.version }}</span></div><span class="dealer-status" :data-status="channel.published ? 'ACTIVE' : 'SUSPENDED'">{{ channel.published ? '已发布' : '未发布' }}</span><div class="dealer-row-actions"><button class="secondary-button" type="button" @click="edit(channel)">编辑</button><button :class="channel.published ? 'danger-button' : 'primary-button'" type="button" @click="toggle(channel)">{{ channel.published ? '下线' : '发布' }}</button></div></article></div></section></SiteShell></template>
