// Reveal semantic blocks; the controller suppresses targets inside another target.
// Keep layout roots out so long pages can reveal their sections as they enter view.
export const ENTRANCE_TARGETS = [
  '[data-reveal]',

  // Shared navigation, footer, and standalone artwork / icons.
  '.wm-header > .wm-brand',
  '.wm-navigation',
  '.wm-auth-nav',
  '.wm-header-actions',
  '.wm-portal-label',
  '.wm-mobile-menu',
  '.wm-quick-panel',
  '.wm-sidebar > .wm-eyebrow',
  '.wm-sidebar nav > a',
  '.wm-sidebar-note',
  '.wm-sidebar-signout',
  '.wm-footer > *',
  '.sketch-icon',
  '.product-artwork',
  '.product-thumbnail',
  '.profile-play-illustration',

  // Home lettering already has its own stroke animation.
  '.home-hero > .wm-eyebrow',
  '.home-explore',
  '.home-dev-link',

  // Catalog: reveal outside the Three.js renderer and its moving paper.
  '.shop-heading',
  '.shop-categories > .shop-section-label',
  '.shop-categories > button',
  '.shop-filter-form',
  '.shop-toolbar',
  '.shop-tile',
  '.shop-pagination',
  '.detail-back',
  '.product-gallery',
  '.product-intro',
  '.product-guide',
  '.product-specifications',
  '.product-safety',

  // Account screens: preserve the desktop columns and stagger their contents.
  '.story-panel > .wm-eyebrow',
  '.wm-auth-story',
  '.wm-auth-icons > span',
  '.story-panel > .hand-note',
  '.form-panel',
  '.account-heading',
  '.account-person',
  '.account-group-label',
  '.account-nav-link',
  '.account-help',
  '.account-information',
  '.account-partnership',
  '.account-signature',

  // Cart, checkout, and order snapshots; cards carry their inner product images.
  '.commerce-page-head',
  '.commerce-filter-panel',
  '.commerce-results-meta',
  '.commerce-order-row',
  '.commerce-list-header',
  '.commerce-cart-row',
  '.commerce-summary',
  '.checkout-card',
  '.commerce-detail-lead',
  '.commerce-detail-section',
  '.commerce-amount-card',
  '.commerce-back-link',
  '.commerce-pagination',

  // Administration, dealership, and support share these section/card patterns.
  '.page-heading',
  '.back-link',
  '.admin-stats',
  '.paper-section',
  '.table-wrap',
  '.pagination',
  '.category-intro',
  '.category-card',
  '.user-hero',
  '.editor-masthead',
  '.dashboard-range-form',
  '.dashboard-card',
  '.dealer-public-hero',
  '.dealer-filter',
  '.channel-card',
  '.dealer-callout',
  '.dealer-product-card',
  '.dealer-detail-head',
  '.dealer-list > article',
  '.company-grid > article',
  '.support-page-intro',
  '.support-detail-lead',
  '.support-aside-card',

  // Loading / empty states and dialog surfaces (never the full-screen overlay).
  '.state-panel',
  '.shop-state',
  '.commerce-state-panel',
  '.dealer-empty',
  '.wm-not-found',
  '.el-dialog',
  '.el-message-box',
].join(', ')

// Exclude both the root and descendants, even when a descendant opts in.
export const ENTRANCE_EXCLUSIONS = [
  '[data-reveal="none"]',
  '[data-reveal="none"] *',
  '.wm-preview',
  '.wm-preview *',
  '.wm-preview-space',
  '.home-title',
  '.home-title *',
  '.home-caption',
  '.home-caption *',
  '.handwritten-line',
  '.handwritten-line *',
  '.polaroid-motion-renderer',
  '.polaroid-motion-renderer *',
  '.polaroid-motion-paper',
  '.polaroid-motion-paper *',
  '.sr-only',
  '.skip-link',
  '.loader',
  '[role="alert"]',
  '[role="alert"] *',
  '.error-summary',
  '.error-summary *',
  '.field-error',
].join(', ')
